### ISSUE TITLE
PHP 8 support

### ISSUE THREAD

**Issue by mgoedecke** [sulu/SuluCommentBundle#42]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | yes
| Sulu Version | 2.x
| Browser Version | Browser name and version

#### Actual Behavior

Should work with latest Sulu bundle and PHP 8

Is there already work being done to make this work with PHP 8 and latest Sulu 2.5?

**Comment by Prokyonn** [comment]
Support for the up to date sulu bundles and PHP 8 has been added with https://github.com/sulu/SuluCommentBundle/pull/48

A new release [2.0.0](https://github.com/sulu/SuluCommentBundle/releases/tag/2.0.0) is already tagged
